### Import

In [1]:
import torch
import torch.nn as nn

### Model

In [22]:
model = nn.Sequential(
    nn.Linear(784, 10),
    nn.ReLU(),
    nn.Linear(10, 10), # Output layer with 10 classes
)

In [23]:
model

Sequential(
  (0): Linear(in_features=784, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=10, bias=True)
)

### Data

In [24]:
x = torch.randn(1, 784) # 1 row, 784 features --> 1 sample

In [25]:
x.shape # Vector

torch.Size([1, 784])

In [26]:
x.type  # Tensor

<function Tensor.type>

In [27]:
# Forward pass
out = model(x) # Output from the model

In [28]:
out # logits - raw scores from the model's layer

tensor([[ 0.3434, -0.1530,  0.2898,  0.3143, -0.0977, -0.2819, -0.0884,  0.2840,
         -0.5151,  0.1967]], grad_fn=<AddmmBackward0>)

In [29]:
out.shape

torch.Size([1, 10])

In [30]:
softmax = nn.Softmax(dim=0) # Columns instead of rows
probs = softmax(out)
probs

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], grad_fn=<SoftmaxBackward0>)

In [31]:
softmax = nn.Softmax(dim=1)
probs = softmax(out)
probs # 10 classes

tensor([[0.1318, 0.0803, 0.1250, 0.1280, 0.0848, 0.0705, 0.0856, 0.1242, 0.0559,
         0.1138]], grad_fn=<SoftmaxBackward0>)

In [32]:
output_class = torch.max(probs)

In [33]:
output_class

tensor(0.1318, grad_fn=<MaxBackward1>)

In [34]:
output_class = torch.argmax(probs) # to get the index

In [35]:
output_class # the input image is 8 # y: output from the model

tensor(0)

### Training

In [36]:
# loss calculation
criterion = nn.CrossEntropyLoss() # loss function
target = torch.tensor([8]) # Target class # Y: actual label

loss = criterion(out, target)
loss

tensor(2.8847, grad_fn=<NllLossBackward0>)

In [37]:
model.parameters()

<generator object Module.parameters at 0x7fd7d8707680>

* Optimizers
* Schedulers

In [38]:
optimizer = torch.optim.Adam(model.parameters(), lr = 0.01) # alpha

In [39]:
n_epochs = 10

In [40]:
target = torch.tensor([2])

In [41]:
for epoch in range(n_epochs):
    y_pred = model(x) # Forward pass
    y_probs = nn.Softmax(dim=1)(y_pred) # Softmax
    
    print('epoch: ', epoch,' loss: ', loss.item())

    loss = criterion(y_pred, target) # Loss calculation
    optimizer.zero_grad() # Zero gradients
    loss.backward() # Backpropagation
    optimizer.step() # Update weights

epoch:  0  loss:  2.8846755027770996
epoch:  1  loss:  2.079784870147705
epoch:  2  loss:  0.5715513229370117
epoch:  3  loss:  0.09392207860946655
epoch:  4  loss:  0.014189188368618488
epoch:  5  loss:  0.002301426837220788
epoch:  6  loss:  0.00040880427695810795
epoch:  7  loss:  7.974783511599526e-05
epoch:  8  loss:  1.7165990357170813e-05
epoch:  9  loss:  4.0531076592742465e-06
