### Imports

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

## **Basics**

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr)
print("Data type:", arr.dtype)
print("Array type:", type(arr))

Array: [1 2 3 4 5]
Data type: int64
Array type: <class 'numpy.ndarray'>


* 0-D Arrays

In [5]:
arr = np.array(42)

print(arr)

42


* 1-D Arrays

In [7]:
arr = np.array([1, 2, 3])

print(arr)

[1 2 3]


* 2-D Arrays

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


* 3-D Arrays

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print("Array shape:", arr.shape)
print("Number of dimensions:", arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Array shape: (2, 2, 3)
Number of dimensions: 3


* Higher Dimensions

In [15]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)

print(arr)
print("Number of dimensions:", arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number of dimensions: 5


* Reshape arrays

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape
newarr1 = arr.reshape(2, 3, 2)
print(newarr1)
print("Reshaped array shape:", newarr1.shape)

# Reshape
newarr2 = arr.reshape(4, 3)
print(newarr2)
print("Reshaped array shape:", newarr2.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Reshaped array shape: (2, 3, 2)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshaped array shape: (4, 3)


* Flattening

In [23]:
## Flattening the newarr2

newarr3 = newarr2.flatten()
newarr4 = newarr2.reshape(-1)

print(newarr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


* Iterating

In [25]:
## Iterating newarr1

for x in np.nditer(newarr1):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


* Concatenate

In [30]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [33]:
arr1 = np.array([[1, 2], [3, 4]])
print(arr1)

arr2 = np.array([[5, 6], [7, 8]])
print(arr2)

arr = np.concatenate((arr1, arr2), axis=0) # 1=rows, 0=columns
print(arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


* Splitting
  - vstack()
  - dstack()
  - vsplit()
  - dsplit()
  - hsplit()
  - hstack()
    

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


* Sorting

In [36]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


## **Data Distribution**

#### Normal Distribution

#### Binomial Distribution

#### Poisson Distribution

#### Uniform Distribution

#### Logistic Distribution

### Chi Square Distribution